package com.glodon.gbq.message.po;

// Generated 2014-9-25 10:12:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message")
public class Message implements java.io.Serializable {

	private String messageId;
	private String account;
	private Integer clientType;
	private Boolean viewed;
	private Boolean sended;
	private String message;
	private Integer sender;
	private String code;
	private Date sendTime;

	public Message() {
	}

	public Message(String messageId) {
		this.messageId = messageId;
	}

	public Message(String messageId, String account, Integer clientType,
			Boolean viewed, Boolean sended, String message, Integer sender,
			String code, Date sendTime) {
		this.messageId = messageId;
		this.account = account;
		this.clientType = clientType;
		this.viewed = viewed;
		this.sended = sended;
		this.message = message;
		this.sender = sender;
		this.code = code;
		this.sendTime = sendTime;
	}

	@Id
//	@GenericGenerator(name="generator",strategy="uuid.hex")
//	@GeneratedValue(generator="generator")
	@Column(name = "messageID", unique = true, nullable = false, length = 40)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "account", length = 45)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "clientType")
	public Integer getClientType() {
		return this.clientType;
	}

	public void setClientType(Integer clientType) {
		this.clientType = clientType;
	}

	@Column(name = "viewed")
	public Boolean getViewed() {
		return this.viewed;
	}

	public void setViewed(Boolean viewed) {
		this.viewed = viewed;
	}

	@Column(name = "sended")
	public Boolean getSended() {
		return this.sended;
	}

	public void setSended(Boolean sended) {
		this.sended = sended;
	}

	@Column(name = "message", length = 4000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "sender")
	public Integer getSender() {
		return this.sender;
	}

	public void setSender(Integer sender) {
		this.sender = sender;
	}

	@Column(name = "code", length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sendTime", length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

}
